---
title: "Module1"
author: "Paige Tuttosi"
date: "25/09/2020"
output: html_document
---

```{r}
source('range_to_mean.R')
source('words_split.R')
library(ggplot2)
library(stringr)
library(purrr) # Tidyverse version of apply functions
library(dplyr)
library(lubridate) # For cleaning dates (the confirmed column)
```

```{r}
# Load in the new training data
train <- read.csv("data/train2.txt")
```


```{r, eval = F}
summary(train)
str(train)
```

```{r}
# Clean age ranges by converting age ranges to a single number
train$clean_age <- map_dbl(train$age, range_to_mean)
summary(train)
str(train)
```


Plots of duration vs. clean_age with colors for the other variables to look for linear associations 
```{r, eval = F}
ggplot(train, aes(x=clean_age, y=duration, color=sex)) +
  geom_point()
ggplot(train, aes(x=clean_age, y=duration, color=city)) +
  geom_point()
ggplot(train, aes(x=clean_age, y=duration, color=country)) +
  geom_point()
ggplot(train, aes(x=clean_age, y=duration, color=province)) +
  geom_point()
ggplot(train, aes(x=clean_age, y=duration, color=V1)) +
  geom_point()
ggplot(train, aes(x=clean_age, y=duration, color=outcome)) +
  geom_point()
```

Symptom grouping functions
```{r}
level1_symptoms <- function(words_vector){
  words_vector <- str_replace_all(words_vector, regex(".*musc.*|.*discomfort.*|malaise|myalgia", ignore_case = TRUE), "muscle soreness")
  words_vector <- str_replace_all(words_vector, regex(".*throat.*", ignore_case = TRUE), "sore throat")
  words_vector <- str_replace_all(words_vector, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE), "difficulties breathing")
  words_vector <- str_replace_all(words_vector, regex("diarr.*", ignore_case = TRUE), "diarrhea")
  words_vector <- str_replace_all(words_vector, regex(".*weaK.*", ignore_case = TRUE), "weakness")
  words_vector <- str_replace_all(words_vector, regex("runny nose|rhinorreah", ignore_case = TRUE), "runny nose")
  words_vector <- str_replace_all(words_vector, regex("sputum|expectoration", ignore_case = TRUE), "wet cough")
  
  words_vector <- unique(words_vector)
  
  return(words_vector)
}
```


```{r}
level2_symptoms <- function(words_vector){
  words_vector <- str_replace_all(words_vector, regex(".*musc.*|.*discomfort.*|malaise|myalgia|.*physical.*", ignore_case = TRUE), "muscle soreness")
  words_vector <- str_replace_all(words_vector, regex(".*throat.*", ignore_case = TRUE), "sore throat")
  words_vector <- str_replace_all(words_vector, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE), "difficulties breathing")
  words_vector <- str_replace_all(words_vector, regex("diarr.*", ignore_case = TRUE), "diarrhea")
  words_vector <- str_replace_all(words_vector, regex(".*weak.*", ignore_case = TRUE), "weakness")
  words_vector <- str_replace_all(words_vector, regex("runny nose|rhinorreah", ignore_case = TRUE), "runny nose")
  words_vector <- str_replace_all(words_vector, regex("sputum|expectoration", ignore_case = TRUE), "wet cough")
  words_vector <- str_replace_all(words_vector, regex(".*37.*", ignore_case = TRUE), "low fever")
  words_vector <- str_replace_all(words_vector, regex(".*39.*", ignore_case = TRUE), "high fever")
  
  words_vector <- unique(words_vector)
  
  return(words_vector)
}
```

```{r}
level3_symptoms <- function(words_vector){
  words_vector <- str_replace_all(words_vector, regex(".*musc.*|.*discomfort.*|malaise|myalgia|.*physical.*", ignore_case = TRUE), "muscle soreness")
  words_vector <- str_replace_all(words_vector, regex(".*throat.", ignore_case = TRUE), "sore throat")
  words_vector <- str_replace_all(words_vector, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE), "difficulties breathing")
  words_vector <- str_replace_all(words_vector, regex("diarr.*", ignore_case = TRUE), "diarrhea")
  words_vector <- str_replace_all(words_vector, regex(".*weak.*", ignore_case = TRUE), "weakness")
  words_vector <- str_replace_all(words_vector, regex("runny nose|rhinorreah", ignore_case = TRUE), "runny nose")
  words_vector <- str_replace_all(words_vector, regex("sputum|expectoration", ignore_case = TRUE), "wet cough")
  words_vector <- str_replace_all(words_vector, regex(".*37.*", ignore_case = TRUE), "low fever")
  words_vector <- str_replace_all(words_vector, regex(".*chest.*", ignore_case = TRUE), "chest pain")
  words_vector <- str_replace_all(words_vector, regex(".*pneu.*|.*respir.*", ignore_case = TRUE), "respiratory difficulties")
  words_vector <- str_replace_all(words_vector, regex(".*39.*|fever", ignore_case = TRUE), "high fever")
  words_vector <- str_replace_all(words_vector, regex(".*cough.*|sneeze", ignore_case = TRUE), "dry cough")
  words_vector <- str_replace_all(words_vector, regex(".*dry.*", ignore_case = TRUE), "dryness")
  
  words_vector <- unique(words_vector)
  
  return(words_vector)
}
```

```{r}
detect_level1 <- function(df, word_vector) {
  
  for( i in c(0:length(words_vector) ) ){
      if(word_vector[i] == "muscle soreness"){
        df$word_vector <- str_detect(df$symptoms, regex(".*musc.*|.*discomfort.*|malaise|myalgia", ignore_case = TRUE))
      }else if (word_vector[i] =="sore throat"){
        df$word_vector <- str_detect(df$symptoms, regex(".*throat.*", ignore_case = TRUE))
      }else if (word_vector[i] == "difficulties breathing"){
        df$word_vector <- str_detect(df$symptoms, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE))
      }else if (word_vector[i] == "weakness"){
        df$word_vector <- str_detect(df$symptoms, regex(".*weak.*", ignore_case = TRUE))
      }else if (word_vector[i] == "diarrhea"){
        df$word_vector <- str_detect(df$symptoms, regex("diarr.*", ignore_case = TRUE))
      }else if (word_vector[i] == "runny nose"){
        df$word_vector <- str_detect(df$symptoms, regex("runny nose|rhinorreah", ignore_case = TRUE))
      }else if (word_vector[i] == "wet cough"){
        df$word_vector <- str_detect(df$symptoms, regex("sputum|expectoration", ignore_case = TRUE))
      }else{
        df$word_vector <- str_detect(df$symptoms, words_vector[i])
      }
  }
}
```

```{r}
detect_level2 <- function(df, word_vector) {
  
  for( i in c(0:length(words_vector) ) ){
      if(word_vector[i] == "muscle soreness"){
        df$word_vector <- str_detect(df$symptoms, regex("musc.*|.*musc|discomfort.*|.*discomfort|malaise|myalgia|.*physical|pysical.*", ignore_case = TRUE))
      }else if (word_vector[i] =="sore throat"){
        df$word_vector <- str_detect(df$symptoms, regex(".*throat.*", ignore_case = TRUE))
      }else if (word_vector[i] == "difficulties breathing"){
        df$word_vector <- str_detect(df$symptoms, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE))
      }else if (word_vector[i] == "weakness"){
        df$word_vector <- str_detect(df$symptoms, regex(".*weak.*", ignore_case = TRUE))
      }else if (word_vector[i] == "diarrhea"){
        df$word_vector <- str_detect(df$symptoms, regex("diarr.*", ignore_case = TRUE))
      }else if (word_vector[i] == "runny nose"){
        df$word_vector <- str_detect(df$symptoms, regex("runny nose|rhinorreah", ignore_case = TRUE))
      }else if (word_vector[i] == "wet cough"){
        df$word_vector <- str_detect(df$symptoms, regex("sputum|expectoration", ignore_case = TRUE))
      }else if (word_vector[i] == "low fever"){
        df$word_vector <- str_detect(df$symptoms, regex(".*37.*", ignore_case = TRUE))
      }else if (word_vector[i] == "high fever"){
        df$word_vector <- str_detect(df$symptoms, regex(".*39.*", ignore_case = TRUE))
      }else{
        df$word_vector <- str_detect(df$symptoms, words_vector[i])
      }
  }
}
```

```{r}
detect_level2 <- function(df, word_vector) {
  
  for( i in c(0:length(words_vector) ) ){
      if(word_vector[i] == "muscle soreness"){
        df$word_vector <- str_detect(df$symptoms, regex("musc.*|.*musc|discomfort.*|.*discomfort|malaise|myalgia|.*physical|pysical.*", ignore_case = TRUE))
      }else if (word_vector[i] =="sore throat"){
        df$word_vector <- str_detect(df$symptoms, regex(".*throat.*", ignore_case = TRUE))
      }else if (word_vector[i] == "difficulties breathing"){
        df$word_vector <- str_detect(df$symptoms, regex(".*breath.*|.*dyspnea.*", ignore_case = TRUE))
      }else if (word_vector[i] == "weakness"){
        df$word_vector <- str_detect(df$symptoms, regex(".*weak.*", ignore_case = TRUE))
      }else if (word_vector[i] == "diarrhea"){
        df$word_vector <- str_detect(df$symptoms, regex("diarr.*", ignore_case = TRUE))
      }else if (word_vector[i] == "runny nose"){
        df$word_vector <- str_detect(df$symptoms, regex("runny nose|rhinorreah", ignore_case = TRUE))
      }else if (word_vector[i] == "wet cough"){
        df$word_vector <- str_detect(df$symptoms, regex("sputum|expectoration", ignore_case = TRUE))
      }else if (word_vector[i] == "low fever"){
        df$word_vector <- str_detect(df$symptoms, regex(".*37.*", ignore_case = TRUE))
      }else if (word_vector[i] == "high fever"){
        df$word_vector <- str_detect(df$symptoms, regex(".*39.*", ignore_case = TRUE))
      }else if (word_vector[i] == "chest pain"){
        df$word_vector <- str_detect(df$symptoms, regex(".*chest.*", ignore_case = TRUE))
      }else if (word_vector[i] == "respiratory difficulties"){
        df$word_vector <- str_detect(df$symptoms, regex(".*pneu.*|.*respir.*", ignore_case = TRUE))
      }else if (word_vector[i] == "dry cough"){
        df$word_vector <- str_detect(df$symptoms, regex(".*cough.*|sneeze", ignore_case = TRUE))
      }else if (word_vector[i] == "dryness"){
        df$word_vector <- str_detect(df$symptoms, regex(".*dry.*", ignore_case = TRUE))
      }else{
        df$word_vector <- str_detect(df$symptoms, words_vector[i])
      }
  }
}
```

Clean symptoms
```{r}
# Create a vector of symptoms, with each element corresponding to a symptom
words1 <- words_split(train$symptoms, sep = "; ")

# Looking at the frequencies of the symptoms
sort(table(words1), decreasing = T)

# Get the unique symptoms
words2 <- words1 %>%
  unique() %>%
  # Replace the "℃" with "C"
  str_replace_all("℃", "C") %>%
  # Replace " ° " with " "
  str_replace_all(" ° ", " ")

# Initialize a dataframe
symptoms_df <- data.frame(matrix(nrow = nrow(train),
                                 ncol = length(words2)))
# Create column names from the unique symptoms
colnames(symptoms_df) <- words2
                      
# Create the vectors for the columns
for( i in c( 1:length(words2) ) ){
  # Each column indicates if the word is present in the symptoms column
  symptoms_df[ , i] <- str_detect(train$symptoms, words2[i])
}

# Combine the original train data frame with the new symptoms data frame
train_full <- cbind(train, symptoms_df)
```

Symptom grouping testing
```{r, eval = F}
# Create the various symptom binning levels
words3 <- level1_symptoms(words2)
words4 <- level2_symptoms(words2)
words5 <- level3_symptoms(words2)

# Initialize a dataframe
symptoms_df_level1 <- data.frame(matrix(nrow = nrow(train),
                                        ncol = length(words3)))
# Create column names from the unique symptoms
colnames(symptoms_df_level1) <- words3

# Create the vectors for the columns
for( i in c( 1:length(words3) ) ){
  # Each column indicates if the word is present in the symptoms column
  symptoms_df_level1[ , i] <- str_detect(train$symptoms, words3[i])
}

# Combine the original train data frame with the new symptoms data frame
train_full_level1 <- cbind(train, symptoms_df_level1)

# Initialize a dataframe
symptoms_df_level2 <- data.frame(matrix(nrow = nrow(train),
                                        ncol = length(words4)))
# Create column names from the unique symptoms
colnames(symptoms_df_level2) <- words4

# Create the vectors for the columns
for( i in c( 1:length(words4) ) ){
  # Each column indicates if the word is present in the symptoms column
  symptoms_df_level2[ , i] <- str_detect(train$symptoms, words4[i])
}

# Combine the original train data frame with the new symptoms data frame
train_full_level2 <- cbind(train, symptoms_df_level2)

# Initialize a dataframe
symptoms_df_level3 <- data.frame(matrix(nrow = nrow(train),
                                        ncol = length(words5)))
# Create column names from the unique symptoms
colnames(symptoms_df_level3) <- words5

# Create the vectors for the columns
for( i in c( 1:length(words5) ) ){
  # Each column indicates if the word is present in the symptoms column
  symptoms_df_level3[ , i] <- str_detect(train$symptoms, words5[i])
}

# Combine the original train data frame with the new symptoms data frame
train_full_level3 <- cbind(train, symptoms_df_level3)
```




Dataframe cleaning function
```{r}
clean_confirmed_age_and_symptoms <- function(df1, df2, symptom_level = 0){
  # This function just applies all of the cleaning steps to the
  # Stat 440 module 1 covid data sets. The function accepts a dataframe to
  # obtain the symptoms from, a dataframe to apply the cleaning to, and a
  # numeric symptom level. This function outputs the cleaned dataframe (df2).
  # The symptom level ranges from 0 to 3, with 0 being no symptom binning
  # and 1-3 containing some symptom binning
  
  library(purrr)
  library(dplyr)
  library(stringr)
  library(lubridate)
  source('range_to_mean.R')
  source('words_split.R')
  
  # Clean confirmed dates with lubridate
  df1$confirmed <- dmy(df1$confirmed)
  
  # Clean age ranges by converting age ranges to a single number
  df1$clean_age <- map_dbl(df1$age, range_to_mean)
  
  # Create a vector of symptoms, with each element corresponding
  # to a symptom
  words1 <- words_split(df1$symptoms, sep = "; ")
  
  # Get the unique symptoms
  words2 <- words1 %>%
    unique() %>%
    # Replace the "℃" with "C"
    str_replace_all("℃", "C") %>%
    # Replace " ° " with " "
    str_replace_all(" ° ", " ")
  
  if(symptom_level == 1){
    words2 <- level1_symptoms(words2)
  }
  else if(symptom_level == 2){
    words2 <- level2_symptoms(words2)
  }
  else if(symptom_level == 3){
    words2 <- level3_symptoms(words2)
  }
  
  # Initialize a dataframe
  symptoms_df <- data.frame(
    matrix(nrow = nrow(df2),
           ncol = length(words2))
    )
  # Create column names from the unique symptoms
  colnames(symptoms_df) <- words2
  
  # Create the vectors for the columns
  for( i in c( 1:length(words2) ) ){
    # Each column indicates if the word is present in the symptoms column
    symptoms_df[ , i] <- str_detect(df2$symptoms, words2[i])
  }
  # Combine the original train data frame with the new symptoms data frame
  df2 <- cbind(df2, symptoms_df)
  
  # Remove the intermediate variables
  rm(symptoms_df, words1, words2, i)
  
  # Return the new dataframe
  return(df2)
}
```

Clean the test data set
```{r}
# test2 <- read.csv("data/test2.txt")
# 
# test2 <- clean_confirmed_age_and_symptoms(test2)
# 
# test2$symptoms <- NULL
# test2$confirmed <- NULL
# 
# # Export the new test dataset
# write.csv(test2, "data/test2_cleaned.csv")
# 
# # Consideration: the new test data set might have indicator symptom
# # variables that aren't present in even the other three data sets.
```


Clean the other data sets
```{r}
# Copying the new training set
train_new <- read.csv("data/train2.txt")
# Remove the "outcome" column for merging purposes
train_new$outcome <- NULL

# Clean the df
train_new <- clean_confirmed_age_and_symptoms(train_new)

# Consideration: Not sure what to do with the outcome column in the
# old test set; not sure if they are actually all blank or missing

# Create a separate cleaned training set if we can't use old data
```

Fixing column issues
```{r}
# Merge the training and test data sets so that they all have the same
# columns

test2 <- read.csv("data/test2.txt")

# Remove the id column
test2$Id <- NULL

# Add an empty duration column for test2
test2$duration <- as.numeric(NA)

# test2$clean_age <- map_dbl(test2$age, range_to_mean)
# 
# test2$confirmed <- dmy(test2$confirmed)

# Check the first few column names
head(colnames(train_new), 10)
head(colnames(test2), 10)

# Check the first few column names
head(colnames(train_new), 10)
head(colnames(test2), 10)

# Create a vector of symptoms, with each element corresponding
# to a symptom
words1 <- words_split(train_new$symptoms, sep = "; ")
  
# Get the unique symptoms
words2 <- words1 %>%
  unique() %>%
  # Replace the "℃" with "C"
  str_replace_all("℃", "C") %>%
  # Replace " ° " with " "
  str_replace_all(" ° ", " ")
  
# Initialize a dataframe
symptoms_df <- data.frame(
  matrix(nrow = nrow(test2),
         ncol = length(words2))
  )

colnames(symptoms_df) <- words2
  
# Create the vectors for the columns
for( i in c( 1:length(words2) ) ){
  # Each column indicates if the word is present in the symptoms column
  symptoms_df[ , i] <- str_detect(test2$symptoms, words2[i])
}
# Combine the original train data frame with the new symptoms data frame
test2 <- cbind(test2, symptoms_df)
  
# Remove the intermediate variables
rm(symptoms_df, words1, words2, i)

# Fix column name issue
##colnames(test2)[65] <- "fever (38-39 C)"

# Merge the training and test datasets
full_df1 <- rbind(train_new, test2)

# Remove the old symptoms column
full_df1$symptoms <- NULL
```


Exporting to Python
```{r}
# Split the fully merged data set
train2 <- full_df1[0:219, ]
test2 <- full_df1[220:419, ]

# Export the merged data sets that all have duration
write.csv(train2, "data/train2.csv")

# Export the new test set
write.csv(test2, "data/test2.csv")
```
